export class Pasien {
  id_antrian : string |null|undefined
  id_klinik : string |null|undefined
  id_pasien : string |null|undefined
  agama : string |null|undefined
  alamat : string |null|undefined
  alergi : string |null|undefined
  berat_badan : string |null|undefined
  catatan_khusus : string |null|undefined
  created_at : string |null|undefined
  desa : string |null|undefined
  golongan_darah : string |null|undefined
  jenis_alamat : string |null|undefined
  jenis_kelamin : string |null|undefined
  kabupaten : string |null|undefined
  kdProvider_bpjs : string |null|undefined
  kecamatan : string |null|undefined
  kewarganegaraan : string |null|undefined
  kode_rm : string |null|undefined
  full_rm : string |null|undefined
  nama : string |null|undefined
  umur : string |null|undefined
  nama_panggilan : string |null|undefined
  nik : string |null|undefined
  nmProvider_bpjs : string |null|undefined
  no_bpjs : string |null|undefined
  no_hp : string |null|undefined
  kode_phone: string |null|undefined
  no_reg_pasien : string |null|undefined
  no_rm : string |null|undefined
  pekerjaan : string |null|undefined
  provinsi : string |null|undefined
  status_bpjs : string |null|undefined
  status_input_pasien : string |null|undefined
  status_perkawinan : string |null|undefined
  tanggal_daftar : string |null|undefined
  tempat_lahir : string |null|undefined
  tgl_lahir : string |null|undefined
  tinggi_badan : string |null|undefined
}
