export const ROUTES: any[] = [
   /**DASHBOARD */
   {
    path: "",
    title: "Main",
    moduleName: "",
    iconType: "",
    icon: "",
    class: "",
    groupTitle: true,
    badge: "",
    badgeClass: "",
    role: ["All"],
    submenu: [],
  },
  {
    path: "/admin/welcome",
    title: "Dashboard",
    moduleName: "",
    iconType: "material-icons-two-tone",
    icon: "space_dashboard",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["Demo"],
    submenu: []
  },
  
  /**Role & Right Management */
  {
    path: "",
    title: "ROLE & RIGHTS MANAGEMENT",
    moduleName: "",
    iconType: "",
    icon: "",
    class: "",
    groupTitle: true,
    badge: "",
    badgeClass: "",
    role: ["Demo"],
    submenu: [],
  },
  {
    path: "",
    title: "Role & Right",
    moduleName: "role_right",
    iconType: "material-icons-two-tone",
    icon: "source",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["Demo"],
    submenu: [
      {
        path: "/role-and-rights/tipe-role/view",
        title: "Tipe Role",
        moduleName: "role_right",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
      {
        path: "/role-and-rights/role/view",
        title: "Role Right",
        moduleName: "role_right",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
      // {
      //   path: "/role-and-rights/master-data-user/view",
      //   title: "Akun menu ini pindah ke management akun",
      //   moduleName: "role_right",
      //   iconType: "",
      //   icon: "",
      //   class: "ml-menu",
      //   groupTitle: false,
      //   badge: "",
      //   badgeClass: "",
      //   role: [""],
      //   submenu: [],
      // },


    ]
  },
  {
    path: "",
    title: "Manajemen Akun",
    moduleName: "manajemen_akun",
    iconType: "material-icons-two-tone",
    icon: "source",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["Demo"],
    submenu: [
      {
        path: "/manajemen-akun/akun/view",
        title: "Akun",
        moduleName: "manajemen_akun",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
      {
        path: "/manajemen-akun/staf/view",
        title: "Staf",
        moduleName: "manajemen_akun",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
    ]
  },
  {
    path: "",
    title: "Manajemen Menu",
    moduleName: "manajemen_menu",
    iconType: "material-icons-two-tone",
    icon: "source",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["Demo"],
    submenu: [
      {
        path: "/manajemen-menu/repo/view",
        title: "Repo",
        moduleName: "manajemen_menu",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
      {
        path: "/manajemen-menu/repo-service/view",
        title: "Repo Service",
        moduleName: "manajemen_menu",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
      {
        path: "/manajemen-menu/menu/view",
        title: "Menu",
        moduleName: "manajemen_menu",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
      {
        path: "/manajemen-menu/menu-right/view",
        title: "Menu Right",
        moduleName: "manajemen_menu",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
    ]
  },
  {
    path: "",
    title: "MANAJEMEN KLINIK",
    moduleName: "",
    iconType: "",
    icon: "",
    class: "",
    groupTitle: true,
    badge: "",
    badgeClass: "",
    role: ["Demo"],
    submenu: [],
  },
  {
    path: "",
    title: "Manajemen Klinik",
    moduleName: "manajemen_klinik",
    iconType: "material-icons-two-tone",
    icon: "source",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["Demo"],
    submenu: [
      {
        path: "/manajemen-klinik/master-poli/view",
        title: "Master Poli",
        moduleName: "manajemen_klinik",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
      {
        path: "/manajemen-klinik/daftar-klinik/view",
        title: "Daftar Klinik",
        moduleName: "manajemen_klinik",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
      {
        path: "/manajemen-klinik/daftar-poliklinik/view",
        title: "Daftar Poliklinik",
        moduleName: "manajemen_klinik",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
    ]
  },
  /** MASTER DATA */
  {
    path: "",
    title: "MASTER DATA",
    moduleName: "",
    iconType: "",
    icon: "",
    class: "",
    groupTitle: true,
    badge: "",
    badgeClass: "",
    role: ["Demo"],
    submenu: [],
  },
  {
    path: "/master-data/obat",
    title: "Master Data Obat",
    moduleName: "master_data_obat",
    iconType: "material-icons-two-tone",
    icon: "source",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["Demo"],
    submenu: [],
  },
  {
    path: "",
    title: "Master Tindakan",
    moduleName: "master_tindakan",
    iconType: "material-icons-two-tone",
    icon: "source",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["Demo"],
    submenu: [
      {
        path: "/master-data/tindakan/dokter/view",
        title: "Tindakan Dokter",
        moduleName: "master_tindakan",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
      {
        path: "/master-data/tindakan/fisio-terapi/view",
        title: "Tindakan Fisio",
        moduleName: "master_tindakan",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      }
    ]
  },
  {
    path: "",
    title: "Master Data Industri",
    moduleName: "master_industri",
    iconType: "material-icons-two-tone",
    icon: "source",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["Demo"],
    submenu: [
      {
        path: "/master-data/data-industri/pabrik-obat-alat/view",
        title: "Pabrik Obat & Alat Kesehatan",
        moduleName: "master_industri",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
      {
        path: "/master-data/data-industri/distributor-obat-alat/view",
        title: "Distributor Obat & Alat Kesehatan",
        moduleName: "master_industri",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      }
    ]
  },

  // {
  //   path: "/master-data/poli-klinik",
  //   title: "Master Poli Klinik",
  //   moduleName: "",
  //   iconType: "material-icons-two-tone",
  //   icon: "source",
  //   class: "",
  //   groupTitle: false,
  //   badge: "",
  //   badgeClass: "",
  //   role: ["Demo"],
  //   submenu: [],
  // },
  {
    path: "/master-data/alat-bantu/view",
    title: "Master Alat Bantu",
    moduleName: "",
    iconType: "material-icons-two-tone",
    icon: "source",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["Demo"],
    submenu: [],
  },
  {
    path: "/master-data/rujukan/view",
    title: "Master Rujukan",
    moduleName: "",
    iconType: "material-icons-two-tone",
    icon: "source",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["Demo"],
    submenu: [],
  },
  {
    path: "/master-data/assesment/view",
    title: "Master Assesment",
    moduleName: "",
    iconType: "material-icons-two-tone",
    icon: "source",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["Demo"],
    submenu: [],
  },
  // {
  //   path: "/master-data/poli-klinik",
  //   title: "Master Data Industri",
  //   moduleName: "",
  //   iconType: "material-icons-two-tone",
  //   icon: "source",
  //   class: "",
  //   groupTitle: false,
  //   badge: "",
  //   badgeClass: "",
  //   role: ["Demo"],
  //   submenu: [],
  // },


  /**DATA PASIEN */
  {
    path: "",
    title: "DATA PASIEN",
    moduleName: "",
    iconType: "",
    icon: "",
    class: "",
    groupTitle: true,
    badge: "",
    badgeClass: "",
    role: ["All"],
    submenu: [],
  },
  {
    path: "/pasien/data-pasien/view",
    title: "Data Pasien",
    moduleName: "",
    iconType: "material-icons-two-tone",
    icon: "face",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["Demo"],
    submenu: [],
  },
  {
    path: "",
    title: "Antrean Pasien",
    moduleName: "antrean_pasien",
    iconType: "material-icons-two-tone",
    icon: "face",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["Demo"],
    submenu: [
      {
        path: "/pasien/antrean/pendaftaran-antrean/view",
        title: "Pendaftaran Antrean Pasien",
        moduleName: "antrean_pasien",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
      {
        path: "/pasien/antrean/antrean-pasien/view",
        title: "Antren Pasien",
        moduleName: "antrean_pasien",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
    ]
  },
  /** PERAWAT */
  {
    path: "",
    title: "Perawat",
    moduleName: "",
    iconType: "",
    icon: "",
    class: "",
    groupTitle: true,
    badge: "",
    badgeClass: "",
    role: ["All"],
    submenu: [],
  },
  {
    path: "/perawat/antrean-perawat/view",
    title: "Antrean Perawat",
    moduleName: "",
    iconType: "material-icons-two-tone",
    icon: "people_alt",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["Demo"],
    submenu: []
  },
  {
    path: "/perawat/antrean-rujukan/view",
    title: "Antrean Rujukan Tindakan",
    moduleName: "",
    iconType: "material-icons-two-tone",
    icon: "people_alt",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["Demo"],
    submenu: [],
  },
  /** DOKTER */
  {
    path: "",
    title: "DOKTER",
    moduleName: "",
    iconType: "",
    icon: "",
    class: "",
    groupTitle: true,
    badge: "",
    badgeClass: "",
    role: ["Demo"],
    submenu: [],
  },
  // supervised_user_circle
  {
    path: "/dokter/antrean-dokter/view",
    title: "Antrean Dokter",
    moduleName: "",
    iconType: "material-icons-two-tone",
    icon: "supervised_user_circle",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["Demo"],
    submenu: []
  },
  {
    path: "/dokter/antrean-rujukan/view",
    title: "Antrean Rujukan Dokter",
    moduleName: "",
    iconType: "material-icons-two-tone",
    icon: "supervised_user_circle",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["Demo"],
    submenu: []
  },
  /** FARMASI */
  {
    path: "",
    title: "FARMASI",
    moduleName: "",
    iconType: "",
    icon: "",
    class: "",
    groupTitle: true,
    badge: "",
    badgeClass: "",
    role: ["Demo"],
    submenu: [],
  },
  {
    path: "/farmasi/proses-resep/view",
    title: "Proses Resep Farmasi",
    moduleName: "",
    iconType: "material-icons-two-tone",
    icon: "source",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["Demo"],
    submenu: []
  },
  {
    path: "/farmasi/antrean-resep/view",
    title: "Antrean Resep Farmasi",
    moduleName: "",
    iconType: "material-icons-two-tone",
    icon: "source",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["Demo"],
    submenu: []
  },
  {
    path: "/farmasi/penjualan-obat/view",
    title: "Pejualan Obat",
    moduleName: "",
    iconType: "material-icons-two-tone",
    icon: "source",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["Demo"],
    submenu: []
  },
  {
    path: "",
    title: "Report Farmasi",
    moduleName: "report_farmasi",
    iconType: "material-icons-two-tone",
    icon: "source",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["Demo"],
    submenu: [
      {
        path: "/farmasi/report-farmasi/data-pasien/view",
        title: "Report Data Pasien",
        moduleName: "report_farmasi",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
      {
        path: "/farmasi/report-farmasi/data-transaksi/view",
        title: "Report Data Transaksi",
        moduleName: "report_farmasi",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
    ]
  }
  /**STOK OBAT & ALAT MEDIS */


];
